### PR TITLE
added packages required b/c we vendor python

### PR DESCRIPTION
**Pull request by spgreenberg**
## Changes proposed in this pull request:

These files are necessary because we vendor python. The upstream release includes these in the python package. 

## security considerations

none

### CODE REVIEW

**Comment by bengerman13** [comment]
are there any changes in config/blobs.yml that need to be made?

**Comment by spgreenberg** [comment]
There shouldn't be as these packages are still listed. Though, this makes me question if the upstream versions in python changed. Looking.

**Comment by spgreenberg** [comment]
They did... updating and will resubmit.

**Comment by spgreenberg** [comment]
@bengerman13  urllib3 version bumped but it matches the existing blob already in config/blobs.yml and already uploaded to S3. The other dependencies I removed are already updated in the spec so I removed them from the CG block. This should be ready to try now.

**Pull request merged**
